name: Recovery Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false

    - name: Initialize Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set Up Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync Minimal Manifest
      run: |
        mkdir ~/twrp
        cd ~/twrp
        repo init --depth=1 -u https://github.com -b twrp-12.1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd ~/twrp
        git clone https://github.com -b vnd_kh6_h6513-user-12-SP1A.210812.016-590061-release-keys device/tecno/TECNO-KH6

    - name: Build TWRP
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_TECNO-KH6-eng
        make recoveryimage -j$(nproc --all)

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Recovery-TECNO-KH6
        path: ~/twrp/out/target/product/TECNO-KH6/recovery.img
